### PR TITLE
#1352 support resume

### PR DESCRIPTION
**Pull request by tynorantoni**
Hello!

First of all, the code will not work, because I made back-end controller for updating resume but I need help with implementing that with project. 
I don't know where to start with that so instead of ruining other controllers I'll ask you.

### CODE REVIEW

**Comment by Code4SocialGood** [comment]
@tynorantoni Thanks for the PR!
1. Where is the resume saved to? 
2. Are you able to work on frontend also? If yes, then you could write frontend code to test the backend restful service. Otherwise, you might want to write unit test at backend to test the backend code.

**Comment by tynorantoni** [comment]
I think the resume will be saved to aws? Am I right? I am currently working at front end part. Maybe this evening I'll commit rest of my issue :)

**Comment by Code4SocialGood** [comment]
@tynorantoni The resume could be saved to Amazon S3, same as images (we store Project Image, Organization Log, and User Avatars in S3). Please refer to the frontend and backend code on saving/retrieving images.

**Comment by Code4SocialGood** [comment]
@tynorantoni I will hold this backend PR, and will merge it after the frontend PR is out and the integration between frontend and backend are tested by you locally.

**Comment by tynorantoni** [comment]
Sorry for delay, I've made some changes and work on front end part. ( https://github.com/Code4SocialGood/c4sg-web/pull/1798 ). 

App is working, but uploading resume to AWS don't. I don't figured yet why after uploading file I've got 404 error caused by "Not expecting a response body".

**Comment by felipealvesgnu** [comment]
@tynorantoni  Do you still need help on that ?

**Pull request closed without merging**
