### PR TITLE
Add Unit Test

### PR DESCRIPTION
**Pull request by jxwang16**

### CODE REVIEW

**Comment by Code4SocialGood** [comment]
@felipealves-gnu 
Please disable Unit Test in Travis Build. In Agile test driven development, all the test cases fail initially. We will run the JUnit tests manually.

**Comment by felipealvesgnu** [comment]
ok

**Comment by felipealvesgnu** [comment]
Even though the tests cases failling in the begging according to TDD. But in terms of Continuous Integration all the test should run before all deploys to guarantee the integrity of the system.

**Comment by Code4SocialGood** [comment]
I could update this Unit Test to comment out the failed portion. Then it will pass Travis CI.

**Pull request merged**
