### PR TITLE
Issue 260 add more info to volunteer application email

### LINKED ISSUE #260: Volunteer Application: Add more info in the email
Class: ProjectServiceImpl.java
Method: apply()
Current email body: 
_You received an application from Code for Social Good. Please login to the dashboard to review the application._

Requirement: 
Add additional information in the email body:
- Project Name
- Applicant First Name + Application Last Name
- Applicant Email Address
- Slack username
- Applicant Title
- Applicant Skills
- Applicant Overview

### PR DESCRIPTION
**Pull request by kulgan**
fixes #260 
Classes: ProjectServiceImpl, AsyncEmailService, AsyncEmailServiceImpl
Requirement: Add extra info to email sent on volunteer application

Implementation Details: 
* Added Thymeleaf templating engine, for HTML email templates. Template are in `resources/templates`
* Retrieved user skills using `SkillsService.findSkillsforUser`
* Applicant slack username => `User.chatUsername`
* Applicant Title => `User.title`
* Applicant Overview => `User.introduction`

### CODE REVIEW

**Comment by Code4SocialGood** [comment]
@kulgan I got compiling errors, how do I resolve them? I am using Eclipse, if that matters.

image

image

**Comment by kulgan** [comment]
You need to refresh your gradle project - Right click the project -> Select gradle -> Gradle refresh

**Comment by Code4SocialGood** [comment]
@kulgan 
1. When I run it locally in Eclipse, it gave ConnectionRefused error, since it used the properties from application-dev.properties. 
2. If I change the spring mail property settings in application-dev.properties to be the same as application.properties, then everything works great.

**Questions**
1. Should we change application-dev.properties to have the same property values as application.properties?
2. If yes, could you make the code change?
3. If no, how should developers run it locally? Hijack the property file and enter their own email properties? It is not very convenient and necessary to do so.

image

image

image

image

**Comment by kulgan** [comment]
We could do 1 & 2 and I make the required code change. The only reason there was a difference was for unit testing. I'll make the modifications and add a specific application.properties for unit testing

**Pull request merged**
