### PR TITLE
User controller test

### PR DESCRIPTION
**Pull request by joshisayali**
Hi,

The testGetDevelopers() method is commented as it expects UserDTO to be returned but actual method returns user object and thus was getting a compile error. Please let me know which object to use.

Also, what should be the test scenario if the user already exists when creating a new user and user not found when deleting or updating new user?

### CODE REVIEW

**Comment by Code4SocialGood** [comment]
@felipealves-gnu Travis build failed on some of the test cases, could you take a look at why?

**Comment by felipealvesgnu** [comment]
@joshisayali your tests are not passing.
1. Can you try decrease the size of those methods they're too much big and hard to maintain.
2. Delete methods that are using block comments.

**Comment by Code4SocialGood** [comment]
@joshisayali I will take care of this unit test. Please go ahead to pick up another task to work on.

**Comment by joshisayali** [comment]
@Code4SocialGood - okay. But, if I get some guidance I can complete it.

**Pull request closed without merging**
