### PR TITLE
Rest API - Delete Organization - Refactor #162

### PR DESCRIPTION
**Pull request by n-machiavelli**
Rest API
DELETE /api/organizations/{id}

Requirement
When an organization is deleted:

organization table - change status to D
For projects belong to this organization, call delete() from
ProjectService
user_organization table - delete linkage
Delete Logo for this organization

### CODE REVIEW

**Comment by rishisharan** [comment]
I reviewed the code, I tested it and it's not deleting any record.

**Comment by n-machiavelli** [comment]
@rishisharan it is not supposed to do hard delete. can you check the organization record you deleted. The status should be "D" and logo should now be null. 
After this it calls deleteproject for each linked project. This method (already existing) will change the project status to C.
Any user_organization row will be deleted

**Comment by felipealvesgnu** [comment]
@n-machiavelli when you change a status it's an UPDATE operation and not a DELETE operation in terms REST. It's better change the method to use PUT method instead of DELETE !!

**Comment by Code4SocialGood** [comment]
@felipealves-gnu I think we can keep the DELETE operation. 
1. The endpoint is the specification that released to the consumer. It reflects the system response in the consumer's perspective, by hiding the implementation details. When end user deletes a project, then simply call the DELETE, it is straightforward. 
2. DELETE endpoint on organization doesn't related to organization itself. It is an multi-step operations: status change on organization entity, delete on linkage object, etc. So it is not 1:1 direct map between endpoint method and entity operation.
3. We maintain the flexibility on the endpoint implementation. It is currently soft delete by changing status, it can be refactored to hard delete later if needed. No matter what the backend implementation is, "DELETE" makes sense to end consumer as a business concept.

**Comment by n-machiavelli** [comment]
Yes the delete requirement here is mostly soft delete as I'm changing status and not deleting the rows.

**Pull request merged**
