### PR TITLE
[Review only] Change the logic for create user to check for deleted users

### PR DESCRIPTION
**Pull request by harshareddy75**

### CODE REVIEW

**Comment by harshareddy75** [comment]
First time contributor - please go easy on me :)

This is to solve issue https://github.com/Code4SocialGood/c4sg-services/issues/363

I have done as suggested in the issue. I deleted the user before recreating it as the user could have changed details (like name) and this seemed like cleaner approach than copying everything from the request to the old user. 

Having said that I noticed that the user has a column called status which allows for the value D (deleted). Ideally I think instead of changing the user email address (adding deleted there), I think we should just be changing the status of the user to D (though I am not entirely sure if that will affect any other parts of the system). 

Please let me know your thoughts.

**Comment by Code4SocialGood** [comment]
**Background**
Email address is unique in user table. 
When a new user is registered, the email address shouldn't already exist in user table.

**Scanario**
1. User "test@gmail.com" registered 
A record is inserted into user: id=1, email="test@gmail.com"
2. User "test@gmail.com" deleted the account
The record with "test@gmail.com" is changed to: id=1, status = 'D', email = 'test@gmail.com-deleted'
3. User  "test@gmail.com" later changed his mind and want to register again
A record is inserted into user, id=2, email="test@gmail.com"
4. User "test@gmail.com" deleted the account
The record with "test@gmail.com" should changed to: id=2 status = 'D', email = 'test@gmail.com-deleted'
Now, this call blows up because id=1 already has email of 'test@gmail.com-deleted'. The user table doesn't allow two records with the same email address.

**Resolution**
What we could do: An easier way is that instead of append with '-deleted', we append with timestamp. 
- When the user deleted account the first time, the email becomes 'test@gmail.com-201711221105'
- When the user deleted account the first time, the email becomes 'test@gmail.com-201711221106'
- To implement this approach, the only change needed is replace "`-deleted`" with current_timestamp (convert it to text format)

```
public void deleteUser(Integer id)
    {    	
        User user = userDAO.findById(id);      
        user.setStatus(Constants.USER_STATUS_DELETED); // Change user status to 'D'
        user.setEmail(user.getEmail() + "-deleted"); // Append to email address "-deleted"
        userDAO.save(user);        
    }
```

**Comment by jekcosty** [comment]
I would have to disagree on altering values of the email id to indicate a change in state of a user.
An attribute of an object should serve its purpose and for only one purpose.
Attributes can be added to further define characteristics of the entity. 
I would rather expect a column of an 'effective termination date' to indicate along perhaps with the status of say "D" for "Deleted" or "Deactivated" depending on the business need. If a reactivation scenario occurs due to a found User row, then perhaps clear the effective termination date and set the status to 'A'. My assumption for this recommendation is that nothing was done on the Auth0 side when the user was deleted, meaning to say that the entry was not deleted in the Auth0 user db.

**Comment by trishulpani** [comment]
@jekcosty Agreed. Changing user's email ID to indicate anything other than its intended purpose should not be encouraged. Perhaps the functionality should be renamed to 'Deactivate account' - thereby allowing the system to indicate the status of the user by manipulating the status flag. If the user tries to register with the same email ID again, the system can prompt if they want to re-activate (assuming it's in a deactivated state).

**Comment by harshareddy75** [comment]
@Code4SocialGood @jekcosty @trishulpani 

if everybody agrees on the approach of just using the status to track the status, I can start changing the service to handle it in that way. I at this moment do not have full information about the rest of the system and apart from testing, I will also have to rely on you guys to help me figure out if this will cause any other problems. 

One use case for example is - if just the status is changed, can the user still login (I will try and check that as well)

Also given that this is a fairly low priority use and corner case - should we just aim for a simple solution?

**Comment by jekcosty** [comment]
I wish it was that easy.
To avoid having someone impersonate another individual using email id, if the system detects that the email id used in the registration already exists in the system, a verification email needs to be sent to that email address. 
This would require additional steps done on the 'deactivation' step, which is to set the 'email verified' attribute to 'false' for the user in Auth0. This step can be done manually or automated using the Auth0 management API.
With this step done, next time the user wants to reactivate his account, he'll be asked for verification and this step requires a change in Auth0 which is to re-send the verification email.
Once verified, and user is found in C4SG db, update the status to 'A'.

A simplified approach is to just delete the user in C4SG db and the Auth0 user db, especially if there's no value in keeping the deactivated account anyways.

**Comment by Code4SocialGood** [comment]
1. There is a PR for deleting user from Auth0 (https://github.com/Code4SocialGood/c4sg-services/pull/307). However, any call to Auth0 API is risky. Unless @jekcosty review and approve that PR, I would rather perform delete from Auth0 manually.

2. Deleting User user story happens very rarely. A low priority task. Any approach should be fine, either a temp solution of just changing user status and email in database, or a full solution of cleaning up in database and Auth0.

3. Or we could just keep the code as it is, revisit later when we have real need. 

All up to you guys, @jekcosty @harshareddy75 @trishulpani

**Comment by felipealvesgnu** [comment]
@jekcosty Could you follow up this ?

**Pull request closed without merging**
