### PR TITLE
Rest API - User - Geocoding #129

### PR DESCRIPTION
**Pull request by joshisayali**
Kindly review and let me know in case of changes.

### CODE REVIEW

**Comment by joshisayali** [comment]
I will look into it.

**Comment by Code4SocialGood** [comment]
1. From swagger UI, create a user by following input parameters:
```
{
  "avatarUrl": "string",
  "chatFlag": "Y",
  **"city": "San Francisco",
  "state": "CA",
  "country": "USA",
  "zip": "94016",**
  "email": "testuser@gmail.com",
  "firstName": "string",
  "forumFlag": "N",
  "gitHubUrl": "string",
  "introduction": "string",
  "lastName": "string",
  "linkedinUrl": "string",
  "personalUrl": "string",
  "phone": "string",
  "publicProfileFlag": "N",
  "resumeUrl": "string",
  "role": "VOLUNTEER",
  "status": "ACTIVE",
  "title": "string",
  "userName": "string",
  "developerFlag": "Y"
}
```
2. Query String generated: 
http://nominatim.openstreetmap.org/search?q=San+Francisco%2CCA%2C94016%2CUSA&format=json&addressdetails=1

3. JSON returned: []

4. If you modify the query string as: `http://nominatim.openstreetmap.org/search?q=San+Francisco+CA+94016+USA&format=json&addressdetails=1`, and type in the browser, you will receive JSON data: 
`[{"place_id":"158675742","licence":"Data © OpenStreetMap contributors, ODbL 1.0. http:\/\/www.openstreetmap.org\/copyright","osm_type":"relation","osm_id":"111968","boundingbox":["37.6403143","37.9298443","-123.1738249","-122.2817799"],"lat":"37.7792808","lon":"-122.4192362","display_name":"San Francisco, San Francisco City and County, California, United States of America","class":"place","type":"city","importance":0.98836369596997,"icon":"http:\/\/nominatim.openstreetmap.org\/images\/mapicons\/poi_place_city.p.20.png","address":{"city":"San Francisco","county":"San Francisco City and County","state":"California","country":"United States of America","country_code":"us"}}]`

**Comment by joshisayali** [comment]
Okay. So how should I form the address part of the URL? Separated by '+'. Currently, I separate by ','

**Comment by joshisayali** [comment]
I tested Santa Clara,CA,95050,USA and it worked.

**Pull request merged**
